version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: "rabbitmq"
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=passwd
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge
